name: qr_scanner
description: QR Scanner

publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  custom_navigation_bar: ^0.8.2
  extended_image: ^4.1.0
  flutter_icons: ^1.1.0
  fluttercontactpicker: ^4.5.1
  gallery_saver: ^2.1.0
  google_fonts: ^2.1.0
  image_editor: ^1.0.0
  image_gallery_saver: ^1.6.9
  image_picker: ^0.8.1+1
  path: ^1.8.0
  permission_handler: ^8.1.1
  photo_view: ^0.11.1
  qrscan: ^0.3.2
  share: ^2.0.4
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.7
  wc_flutter_share: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
